modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="all_the_elements"
version="5.3.0"
displayName="ALL THE ELEMENTS"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Usuari, MCreator"

[[dependencies.all_the_elements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




